<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>gradcast-api-development-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\data\GradCast.Data.csproj" />
  </ItemGroup>

  <Target Name="IncludeWebDistOnPublish" AfterTargets="ComputeFilesToPublish" Condition="Exists('../web/dist')">
    <ItemGroup>
      <DistFiles Include="../web/dist/**/*.*" />
      <ResolvedFileToPublish Include="@(DistFiles)" RelativePath="wwwroot/%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
  </Target>

</Project>
